# tools/dump_asset_structure.py
"""Dump a Unity project's Assets/ folder structure to STRUCTURE.md.

Folded, deterministic directory tree with per-folder extension counts.
Gitignored subtrees (e.g. Vendor/) are truncated 2 levels deep with a
recursive rollup at the cut, so vendor-internal noise collapses to a
per-package inventory line while our own tree shows in full.
"""
import argparse
import os
import subprocess
import sys
from collections import Counter
from pathlib import Path

TRUNCATE_DEPTH = 2          # levels below the topmost gitignored dir
META_EXT = ".meta"

HEADER = (
    "# Asset structure — {project}\n"
    "_Generated by tools/dump_asset_structure.py — do not hand-edit; regenerated by the pre-commit hook._\n"
    "_Vendor↔avatar linkage below is by folder-name convention only, "
    "not authoritative (see docs/LAYOUT.md)._\n\n"
)


def ext_counts(filenames):
    """Counter of extension -> count, excluding .meta; extensionless -> '(no ext)'."""
    c = Counter()
    for name in filenames:
        if name.endswith(META_EXT):
            continue
        ext = Path(name).suffix.lower()
        c[ext if ext else "(no ext)"] += 1
    return c


def format_counts(counter):
    """'1 .mat, 2 .png' sorted by extension label; '' when empty."""
    if not counter:
        return ""
    return ", ".join(f"{counter[ext]} {ext}" for ext in sorted(counter))


def recursive_counts(tree, dir_rel):
    """Sum ext_counts over dir_rel and every descendant in the collected tree."""
    c = Counter()
    for rel, node in tree.items():
        if rel == dir_rel or rel.startswith(dir_rel + "/"):
            c.update(ext_counts(node["files"]))
    return c


def collect(assets_dir, project_dir):
    """Walk assets_dir once; return {rel_posix_dir: {'files': [...], 'subdirs': [...]}}.

    Keys are POSIX paths relative to project_dir (e.g. 'Assets/Vendor').
    """
    tree = {}
    for root, dirs, files in os.walk(assets_dir):
        rel = Path(root).relative_to(project_dir).as_posix()
        ordered = sorted(dirs, key=str.lower)
        dirs[:] = ordered  # sorted walk order; subdirs below is built from this same sorted list
        subdirs = [(Path(root) / d).relative_to(project_dir).as_posix() for d in ordered]
        tree[rel] = {"files": files, "subdirs": subdirs}
    return tree


def render(tree, root_rel, ignored_roots):
    """Return a list of text lines for the folded tree rooted at root_rel.

    ignored_roots: set of topmost gitignored dir rel-paths.
    """
    lines = []

    def walk(dir_rel, indent, depth_under_ignore):
        node = tree[dir_rel]
        name = dir_rel.rsplit("/", 1)[-1]
        is_ignored_root = dir_rel in ignored_roots
        if is_ignored_root:
            depth_under_ignore = 0
        marker = "  (gitignored)" if is_ignored_root else ""

        if depth_under_ignore is not None and depth_under_ignore >= TRUNCATE_DEPTH:
            counts = format_counts(recursive_counts(tree, dir_rel))
            tail = f"   {counts}   (recursive)" if counts else "   (recursive)"
            lines.append(f"{indent}{name}/{tail}")
            return

        local = format_counts(ext_counts(node["files"]))
        tail = f"   {local}" if local else ""
        lines.append(f"{indent}{name}/{marker}{tail}")
        nd = None if depth_under_ignore is None else depth_under_ignore + 1
        for sub in node["subdirs"]:
            walk(sub, indent + "  ", nd)

    walk(root_rel, "", None)
    return lines


def generate(project_dir):
    """Return the STRUCTURE.md document text for project_dir. Pure: writes nothing.

    Exits non-zero (loudly) if Assets/ is missing.
    """
    project_dir = Path(project_dir).resolve()
    assets = project_dir / "Assets"
    if not assets.is_dir():
        sys.exit(f"error: no Assets/ directory at {assets}")
    tree = collect(assets, project_dir)
    ignored_roots = get_ignored_roots(project_dir, [d for d in tree if d != "Assets"])
    lines = render(tree, "Assets", ignored_roots)
    return HEADER.format(project=project_dir.name) + "\n".join(lines) + "\n"


def get_ignored_roots(project_dir, dirs_rel):
    """Set of topmost gitignored dir rel-paths (forward-slash), via one git call.

    Treats check-ignore exit 0 (matches) and 1 (no matches) as success;
    exit 128 or a missing git binary fails loudly.
    """
    if not dirs_rel:
        return set()
    payload = b"".join(rel.encode("utf-8") + b"\0" for rel in dirs_rel)
    try:
        proc = subprocess.run(
            ["git", "check-ignore", "-z", "--stdin"],
            input=payload, cwd=str(project_dir), capture_output=True,
        )
    except FileNotFoundError:
        sys.exit("error: git not found on PATH; required to detect gitignored content")
    if proc.returncode not in (0, 1):
        sys.exit(
            f"error: git check-ignore failed (exit {proc.returncode}) in {project_dir}: "
            f"{proc.stderr.decode('utf-8', 'replace').strip()}"
        )
    # Strict decode is intentional: stdout echoes back a subset of the exact UTF-8 bytes
    # we sent on stdin, so it cannot fail on valid input — a decode error means a real bug,
    # not bad data. (stderr above uses 'replace' because it is free-form git diagnostics.)
    ignored = {p for p in proc.stdout.decode("utf-8").split("\0") if p}
    topmost = set()
    for rel in ignored:
        parent = rel.rsplit("/", 1)[0] if "/" in rel else ""
        if parent not in ignored:
            topmost.add(rel)
    return topmost


def _resolve_project(arg):
    p = Path(arg)
    if p.is_absolute():
        return p
    workspace_root = Path(__file__).resolve().parent.parent  # tools/ -> workspace
    return workspace_root / arg


def main(argv=None):
    ap = argparse.ArgumentParser(description="Dump a Unity project's Assets/ structure.")
    ap.add_argument("project", nargs="?", default="AvatarProject",
                    help="project dir (absolute, or relative to the workspace root)")
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed STRUCTURE.md is stale; write nothing")
    args = ap.parse_args(argv)

    project = _resolve_project(args.project)
    body = generate(project)
    out_file = project / "STRUCTURE.md"

    if args.check:
        current = out_file.read_bytes().decode("utf-8") if out_file.exists() else None
        if current != body:
            sys.exit(f"error: STRUCTURE.md is stale: {out_file} (run dump_asset_structure.py)")
        return
    with open(out_file, "w", encoding="utf-8", newline="\n") as f:  # newline= avoids 3.10+-only write_text kwarg
        f.write(body)
    print(f"wrote {out_file}")


if __name__ == "__main__":
    main()
